import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, hooks...)

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs/ folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can also create a custom sidebar
  // someSidebar: {
  //   CategoryA: ['type', 'doc1', 'doc2', 'doc3'],
  //   CategoryB: ['type-here'],
  // },
};

export default sidebars;
